### ISSUE TITLE
Add docker-compose.yml environment with reference bacnet implementations for testing.

### ISSUE THREAD

**Issue by dopry** [fh1ch/node-bacstack#102]
There are some reference implementations that could be tested against to confirm compliance.

* [CAS BACnet IP Server](http://bacnetstack.com/#licensing)
* [SCADA Engine BACnet Device Simulator](http://www.scadaengine.com/software6.html)
* [Wacnet](https://hvac.io/docs/wacnet)
* [BACnet Stack](http://bacnet.sourceforge.net/)
* [BACpypes](http://bacpypes.sourceforge.net/index.html)

It would be nice to select one or more as a BACnet network to standardize integration testing.

**Comment by fh1ch** [comment]
Sorry for the delay on this one. The whole project was more or less on ice for a while, since I was busy with other stuff...

I've already added a docker-compose based compliance setup (https://github.com/fh1ch/node-bacstack/blob/master/docker-compose.yml) a while ago. It's based on the C++ bacnet (https://sourceforge.net/projects/bacnet/) simulator, bundled as docker-container (https://github.com/fh1ch/bacstack-compliance-docker). I'll gradually start adding more and more coverage, once a BACNET method becomes more mature.

**Comment by dopry** [comment]
No worries, work and life can get busy.  Awesome to see this. hope all is well!
