### ISSUE TITLE
Still Active?

### ISSUE THREAD

**Issue by CraigZych** [fh1ch/node-bacstack#116]
Is this still being actively developed or will beta be the furthest it ever gets?

**Comment by fh1ch** [comment]
@CraigZych the project is still active, but the progress heavily relies on how much time I have, since this is just a side project of mine. Since building automation is quite a serious topic, I'll keep this project in beta until all functions have proper test coverage. You can follow the progress over here: https://github.com/fh1ch/node-bacstack/issues/1
