### ISSUE TITLE
Reading Trend Log - Log Buffers ( Read Access Denied )

### ISSUE THREAD

**Issue by ryanluton** [fh1ch/node-bacstack#124]
Node Version: `9.8.0`

Node BACstack Version: `Beta 13`

- [x] Bug Report
- [ ] Feature Request
- [x] Question

**Note:** Make sure you have read the [FAQs](https://github.com/fh1ch/node-bacstack/blob/master/FAQ.md)
before logging this issue.

### Feature Request / Question
Recieving a "Error: BacnetError - Class:2 - Code:27 Class:PROPERTY Code:READ_ACCESS_DENIED" while trying to read the log_buffer property of a trend log instance. I've talked to the controller vendor's support just to ensure that there are no read permissions wrapped around the specific controller, and they have assured me there are not. 

Have you had any success reading TL objects?

**Comment by fh1ch** [comment]
@ryanluton thanks for reporting this and sorry for the delay...

I checked within the BACnet standard and found following interesting piece for `Trend Log Object Type - Log_Buffer`:

> The log buffer is not network accessible except through the use of the ReadRange service.

I assume you tried to access the property with the `readProperty` method, since I could reproduce this (per BACnet standard correct) behaviour on one of my devices. This is therefore not a bug, but rather expected. You would have to use the `readRange` (https://github.com/fh1ch/node-bacstack/blob/master/test/integration/read-range.spec.js) method to read the log buffer.

**Note:** The `readRange` method in this stack is still extremely new and I assume it still has some bugs. I'm currently in the process of writing compliance tests against a simulator, which should also cover  the `readRange` method.
