### ISSUE TITLE
encode_application_enumerated is not defined in bacnet-asn1.js

### ISSUE THREAD

**Issue by narbuzov** [fh1ch/node-bacstack#3]
encode_application_enumerated is referenced in bacapp_encode_application_data:

    case baEnum.BacnetApplicationTags.BACNET_APPLICATION_TAG_ENUMERATED:
      encode_application_enumerated(buffer, value.Value);
      break;

but not defined as a function. Here is my version to make it work:

var encode_application_enumerated = module.exports.encode_application_enumerated = function(buffer, value) {
  var len;
  if (value < 0x100) {
    len = 1;
  } else if (value < 0x10000) {
    len = 2;
  } else if (value < 0x1000000) {
    len = 3;
  } else {
    len = 4;
  }
  encodeTag(buffer, baEnum.BacnetApplicationTags.BACNET_APPLICATION_TAG_ENUMERATED, false, len);
  encodeBacnetEnumerated(buffer, value);
};

Thank you!

**Comment by fh1ch** [comment]
Hi @narbuzov 

Thank you also very much for your input here :+1: 

The static code analysis showed that I even forgot to implement some more stubs (around 6). They're now all implemented and the static code analysis is happy now, so something like this shouldn't repeat itself in the future.

The problem is now solved in the latest release "[0.0.1-beta.3](https://github.com/fh1ch/node-bacstack/blob/master/CHANGELOG.md#001-beta3-2017-04-14)".

Cheers
