### ISSUE TITLE
EADDRNOTAVAIL Add error event listener to server

### ISSUE THREAD

**Issue by goliatone** [fh1ch/node-bacstack#7]
Creatomg the server instance in `lib/bacnet-transport.js` and event error listener should be added. 
Otherwise if the provided address does not exist you get an you get an ** EADDRNOTAVAIL** error:

>Error: bind EADDRNOTAVAIL 192.168.1.23:47808

It should be added to [][1]
```js
server.on('error', function(err) {
  console.log(`server error:\n${err.stack}`);
  server.close();
});

// Initialisation
server.bind(settings.port, settings.interface, function() {
    server.setBroadcast(true);
  });
```

You should figure out how you want to handle the error, I would suggest to bubble it up so the developer can decide to _do the right thing_.

[1]:https://github.com/fh1ch/node-bacstack/blob/3dccaf7c0627c59ce742bf9157c71a81494fff4d/lib/bacnet-transport.js#L34

**Comment by fh1ch** [comment]
Hi @goliatone 

Also a big thanks for your input on this issue.

Yes, the error handling is not really existent at this point. However, I'm not really sure how to tackle this, but letting the developer handle it is certainly the right way.

On the other hand, I don't think that closing the server on error is helpful in this regard, as we have to differentiate between transactional errors (failure when sending a message) and initialization errors.

``` js
server.on('error', function(err) {
  server.close();
});
```

Cheers

**Comment by goliatone** [comment]
@fh1ch I forked the project with the idea of making a fix I could use and then make a PR with the implementation as an idea for you. I faced two unrelated issues that prevented me from doing so:
* the code base is structured in a way that would make implementing error handling property more involved than ideal
* the library, ultimately, did not work.

I ran the whoIs function and that returned the expected results. Later when trying to read/write properties the library/connection would timeout. I honestly did not spend any cycles looking into this. I tried another library that wraps a C library, it worked, so I went with [node-bacnet][node-bacnet] . I think it might be a segmentation related issue.

It's a bit of a shame since I had started using this library as the basis of a node-red package. I moved it to use the other [node-bacnet][node-bacnet]

All in all, thanks for your work.

[node-bacnet]:https://github.com/relayr/node-bacnet

**Comment by fh1ch** [comment]
Hi @goliatone 

Thank you very much for the feedback and again, sorry for the delayed reaction here...

As the implementation of this project started with a strong personal need for having readPropertyMultiple in place, all the other function came a bit short and due to missing test coverage of them, would break sometimes. That's also one of the reason, why the version number is still beta.

However, a lot has changed and the encoding part is now more or less feature complete and the test coverage increased to almost **80%**. This means that this library will reach a stable state in the next couple of weeks.

Anyway, errors on the transport layer are now passed to the client so each project can decide what to to (e.g. unload the client using the new `client.close()` function). I will therefore close this issue.
